# Site settings
title: The Azeroth Free Press
header-img: img/home-bg.jpg
email: editor@azeroth.press
description: "An independent press reporting from Argent Dawn EU"
baseurl: ""
url: "http://azeroth.press"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
