# Site settings
title: The Azeroth Free Press
header-img: img/home-bg.jpg
email: euanfjackson@gmail.com
description: "An independent press reporting from Argent Dawn EU"
baseurl: ""
url: "http://csable.github.io"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
